package com.firmino.hinedigital.extensions

import com.firmino.hinedigital.R
import com.firmino.hinedigital.view.theme.ThemeGender

data class Exam(
    val title: String = "",
    val subtitle: String = "",
    val tutorial: String = "",
    val textScore5: String = "",
    val textScore4: String = "",
    val textScore3: String = "",
    val textScore2: String = "",
    val textScore1: String = "",
    val textScore0: String = "",
    val imageId5: Triple<Pair<Int?, Int?>, Pair<Int?, Int?>?, Int?> = Triple(Pair(null, null), null, null),
    val imageId4: Triple<Pair<Int?, Int?>, Pair<Int?, Int?>?, Int?> = Triple(Pair(null, null), null, null),
    val imageId3: Triple<Pair<Int?, Int?>, Pair<Int?, Int?>?, Int?> = Triple(Pair(null, null), null, null),
    val imageId2: Triple<Pair<Int?, Int?>, Pair<Int?, Int?>?, Int?> = Triple(Pair(null, null), null, null),
    val imageId1: Triple<Pair<Int?, Int?>, Pair<Int?, Int?>?, Int?> = Triple(Pair(null, null), null, null),
    val imageId0: Triple<Pair<Int?, Int?>, Pair<Int?, Int?>?, Int?> = Triple(Pair(null, null), null, null),
    val maxScore: Int = 3,
) {
    private fun getImages(score: Int) = listOf(imageId0, imageId1, imageId2, imageId3, imageId4, imageId5)[score]
    fun getScoreTexts() = listOf(textScore0, textScore1, textScore2, textScore3, textScore4, textScore5)
    fun getFirstImage(score: Int, theme: ThemeGender) = if (theme == ThemeGender.FEMALE) getImages(score).first.first else getImages(score).first.second
    fun getSecondImage(score: Int, theme: ThemeGender) = if (getImages(score).second != null) if (theme == ThemeGender.FEMALE) getImages(score).second!!.first else getImages(score).second!!.second else null
    fun getAltImage(score: Int) = getImages(score).third
}

data class Evaluation(
    val title: String,
    val section: String,
    val scored: Boolean = true,
    val exams: List<Exam>,
)

val evaluationsList = listOf(
    Evaluation(
        title = "FUNÇÃO DOS NERVOS CRANIANOS",
        section = "SEÇÃO 1: EXAME NEUROLÓGICO",
        exams = listOf(
            Exam(
                title = "Aparência Facial",
                subtitle = "Em repouso e quando está chorando ou sendo estimulado",
                tutorial = "A maior parte desta seção será feita por meio da observação, enquanto se conversa com os pais/cuidadores, antes de iniciar o exame formal.Se a criança usa óculos ou aparelho auditivo, avalie sem usar estes itens e anote os achados – use isso para pontuar. De maneira ideal veja também como é a resposta usando os itens de ajuda.",
                textScore3 = "Sorri ou reage a estímulos fechando os olhos e fazendo caretas",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Fecha os olhos, mas não aperta, pobre expressão facial",
                textScore0 = "Sem expressões, não reage à estímulos",
            ),
            Exam(
                title = "Movimentos dos olhos",
                tutorial = "Observe os movimentos dos olhos e faça com que a criança siga um alvo claro totalmente na vertical, na horizontal e de forma circular. O alvo deve ser mantido a uma distância de 20-30 cm do bebê e movido a uma velocidade constante de cerca de 3 graus/segundo (Ricci D et al Early Hum Dev 2007). A distância não é tão crítica em crianças mais velhas, a menos que tenham dificuldade em seguir o alvo. Certifique-se de que a criança move os olhos totalmente e não compensa qualquer dificuldade que possa ter movido a cabeça. Observe os olhos quanto a anormalidades como estrabismo, nistagmo, ptose etc. Não fale com a criança durante o teste e certifique-se de não ter objetos visuais mais atraentes dentro de seu campo de visão.",
                textScore3 = "Movimentos normais e coordenados (ambos os lados)",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Intermitente: Desvio dos olhos ou movimentos anormais",
                textScore0 = "Contínuo: Desvio dos olhos ou movimentos anormais",
            ),
            Exam(
                title = "Reposta Visual",
                subtitle = "Testar a capacidade de acompanhar um alvo preto/branco",
                tutorial = "Observe os movimentos dos olhos e faça com que a criança siga um alvo claro totalmente na vertical, na horizontal e de forma circular. O alvo deve ser mantido a uma distância de 20-30 cm do bebê e movido a uma velocidade constante de cerca de 3 graus/segundo (Ricci D et al Early Hum Dev 2007). A distância não é tão crítica em crianças mais velhas, a menos que tenham dificuldade em seguir o alvo. Certifique-se de que a criança move os olhos totalmente e não compensa qualquer dificuldade que possa ter movido a cabeça. Observe os olhos quanto a anormalidades como estrabismo, nistagmo, ptose etc. Não fale com a criança durante o teste e certifique-se de não ter objetos visuais mais atraentes dentro de seu campo de visão.",
                textScore3 = "Acompanha o alvo em um arco completo",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Acompanha o alvo em um arco incompleto ou assimétrico",
                textScore0 = "Não acompanha o alvo",
            ),
            Exam(
                title = "Reposta auditiva",
                subtitle = "Testar a resposta a um chocalho",
                tutorial = "O ideal é ter alguém fora da linha de visão da criança para ajudá-lo a testar a resposta auditiva. Faça isso de cada lado separadamente. Tenha cuidado para que não haja um estímulo visual muito atraente (que pode incluir o seu rosto) no campo de visão da criança, pois ela pode ignorar o estímulo auditivo. Se o teste de audição for difícil e os pais relatarem que a criança fez um teste de audição formal e você não estiver preocupado, pode assumir uma pontuação de 3, mas faça uma anotação sobre isso - mas é melhor testar você mesmo. A audição de uma criança pode se deteriorar após o período neonatal devido, por exemplo, a orelha colada ou CMV. Este é um teste comportamental que mostra que a criança processou o som, bem como o ouviu -portanto, não é o mesmo que os potenciais evocados auditivos do tronco cerebral (ABERs) ou emissões otoacústicas (OAEs).",
                textScore3 = "Reage a estímulos de ambos os lados",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Reação duvidosa aos estímulos ou assimetria de resposta",
                textScore0 = "Sem resposta",
            ),
            Exam(
                title = "Sugar/Deglutir",
                subtitle = "Observe a criança sugando o seio materno ou mamadeira. Se for mais velha, pergunte sobre alimentação, tosse associada e salivação excessiva",
                tutorial = "Observe o rosto da criança para uma variedade de movimentos, a tendência para abrir a boca ou babar. Se ao final do exame você não identificar um problema específico, mas achar que há alguma escassez de movimento marque a coluna 2 (pontuação 2).Da mesma forma, se uma criança não tiver dificuldades definidas para sugar, mastigar ou engolir, mas não se alimentar bem, marque a coluna 2 (pontuação 2). O ideal é observar a criança se alimentar, mas se isso não for possível, pergunte aos pais/responsáveis se eles encontram dificuldades na alimentação ou têm preocupações. Observe se a criança baba ou não fecha bem a boca. Se estiver preocupado, consulte um especialista para uma avaliação mais detalhada.",
                textScore3 = "Boa sucção e deglutição",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Pobre sucção e/ou deglutição",
                textScore0 = "Sem reflexo de sucção, sem deglutição",
            ),
        )
    ),

    Evaluation(
        title = "POSTURA",
        section = "SEÇÃO 1: EXAME NEUROLÓGICO",
        exams = listOf(
            Exam(
                title = "Cabeça",
                tutorial = "De maneira ideal os seguintes itens devem ser avaliados com a criança despida, inclusive sem fraldas. No entanto, se despir a criança provoca incômodo, pelo menos, remova sapatos e meias, calças e macacões grossos.para crianças mais novas você terá que apoiá-las sentadas de maneira suficiente para que você apenas avalie a postura da cabeça.",
                subtitle = "Sentado",
                textScore3 = "Reta; na linha média",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Levemente para o lado ou para trás ou para frente",
                textScore0 = "Acentuadamente para o lado ou para trás ou para frente",
                imageId3 = Triple(Pair(R.drawable.bg_img_103_f, R.drawable.bg_img_103_m), null, R.drawable.bg_img_alt_103),
                imageId2 = Triple(Pair(R.drawable.bg_img_103_f, R.drawable.bg_img_103_m), Pair(R.drawable.bg_img_101_f, R.drawable.bg_img_101_m), null),
                imageId1 = Triple(Pair(R.drawable.bg_img_101_f, R.drawable.bg_img_101_m), null, R.drawable.bg_img_alt_101),
                imageId0 = Triple(Pair(R.drawable.bg_img_100_f, R.drawable.bg_img_100_m), null, R.drawable.bg_img_alt_100),
            ),
            Exam(
                title = "Tronco",
                subtitle = "Sentado",
                tutorial = "Para obter uma pontuação 3, as costas (coluna) precisa estar realmente ereta a maior parte do tempo.",
                textScore3 = "Reto",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Levemente curvado ou inclinado para o lado",
                textScore0 = "Muito curvado; Inclinado para trás; Inclinado para o lado",
                imageId3 = Triple(Pair(R.drawable.bg_img_113_f, R.drawable.bg_img_113_m), null, R.drawable.bg_img_alt_113),
                imageId2 = Triple(Pair(R.drawable.bg_img_113_f, R.drawable.bg_img_113_m), Pair(R.drawable.bg_img_111_f, R.drawable.bg_img_111_m), null),
                imageId1 = Triple(Pair(R.drawable.bg_img_111_f, R.drawable.bg_img_111_m), null, R.drawable.bg_img_alt_111),
                imageId0 = Triple(Pair(R.drawable.bg_img_110_f, R.drawable.bg_img_110_m), null, R.drawable.bg_img_alt_110),
            ),
            Exam(
                title = "Braços",
                subtitle = "Em repouso",
                tutorial = "Observe as posturas dos braços durante o exame. Registre as assimetrias.",
                textScore3 = "Em posição neutra, retos no centro ou levemente fletidos",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Leve: Rotação interna ou rotação externa; Intermitente: Postura distônica",
                textScore0 = "Acentuado: Rotação interna ou rotação externa; Postura distônica; Postura hemiplégica",
            ),
            Exam(
                title = "Mãos",
                tutorial = "Observe as posturas das mãos durante o exame. Registre as assimetrias.",
                textScore3 = "Mãos abertas",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Intermitente: Polegar aduzido ou mão cerrada",
                textScore0 = "Persistente: Polegar aduzido ou mão cerrada",
            ),
            Exam(
                title = "Pernas",
                subtitle = "Sentado, supino e em pe.",
                tutorial = "A maneira como você testará dependerá da idade/habilidades da criança. Observe a postura das pernas em todas as 3 posições, ou seja, deitada, sentada e em pé se possível. Para sentar a criança precisa estar em uma superfície plana e com as pernas retas para frente (chamado Long Sitting, não deve ser feito sentado em uma cadeira). Para crianças que ainda não sentam de forma independente, observe a postura das pernas a partir dos quadris em decúbito dorsal e na posição sentada com apoio.Se a criança ainda não estiver sustentando o peso, observe a postura das pernas apenas em supino e sentado. Faça uma avaliação geral das suas observações – lembre-se, apenas 1 pontuação é dada para este ítem. Se por exemplo a observação sentada está em umam coluna diferente da deitada (ou em pé) faça a média das 2 ou 3 pontuações. Registre as assimetrias.",
                textScore3 = "Capaz de sentar com o tronco reto e pernas retas ou levemente fletidas (pode permanecer sentado com as pernas estendidas) Pernas em posição neutra, retas ou levemente fletidas",
                textScore2 = "Leve: Rotação interna ou rotação externa",
                textScore1 = "Senta com o tronco reto, mas com os joelhos fletidos a 15- 20º; Rotação interna ou rotação externa dos quadris",
                textScore0 = "Incapaz de sentar reto, a menos que os joelhos estejam acentuadamente fletidos (não permanece sentado com as pernas estendidas); Acentuado: Rotação interna ou rotação externa ou extensão ou flexão fixa ou contraturas nos quadris e joelhos",
                imageId3 = Triple(Pair(R.drawable.bg_img_143_f, R.drawable.bg_img_143_m), null, R.drawable.bg_img_alt_143),
                imageId2 = Triple(Pair(R.drawable.bg_img_143_f, R.drawable.bg_img_143_m), Pair(R.drawable.bg_img_141_f, R.drawable.bg_img_141_m), null),
                imageId1 = Triple(Pair(R.drawable.bg_img_141_f, R.drawable.bg_img_141_m), null, R.drawable.bg_img_alt_141),
                imageId0 = Triple(Pair(R.drawable.bg_img_140_f, R.drawable.bg_img_140_m), null, R.drawable.bg_img_alt_140),
            ),
            Exam(
                title = "Pés",
                subtitle = "Em supino e em pé",
                tutorial = "Observar a postura do pé em relação à perna - muitas crianças terão alguma angulação externa do pé (rotação externa) ou eversão do pé, mas geralmente isso vem do quadril e não é genuinamente presente no tornozelo. Registre as assimetrias.",
                textScore3 = "Centralizados na posição neutra; Dedos retos entre semi flexão e extensão (em posição neutra)",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Leve: Rotação interna e rotação externa; Intermitente: Tendência de ficar em pé na ponta dos pés ou com dedos fletidos ou estendidos",
                textScore0 = "Acentuado: Rotação interna ou rotação externa do tornozelo; Persistente: Tendência de ficar em pé na ponta dos pés ou com dedos fletidos ou estendidos",
            ),
        )
    ),

    Evaluation(
        title = "MOVIMENTOS",
        section = "SEÇÃO 1: EXAME NEUROLÓGICO",
        exams = listOf(
            Exam(
                title = "Quantidade",
                subtitle = "Observe a criança deitada em supino",
                tutorial = "Esses itens podem ser observados ao longo da avaliação, mas é necessário observar a criança quanto a quantidade e qualidade dos movimentos. Algumas crianças terão movimentos ligeiramente espasmódicos (espasmos), ou seja, a coluna 3, mas raramente eles caem na coluna 4. Se você julgar que os movimentos não são ideais, mas não se encaixam na coluna 3 então coloque-os na coluna 2. Observe que os itens neste seção não são o mesmo que uma Avaliação dos Movimentos Gerais. É mais uma impressão geral do período em que você está observando a criança – também a maioria das crianças que você está avaliando não está dentro da faixa etária da avaliação do GM.",
                textScore3 = "Normal",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Excessivo ou lento",
                textScore0 = "Mínimo ou nenhum",
            ),
            Exam(
                title = "Qualidade",
                subtitle = "Observe a atividade motora espontânea voluntária do bebê durante a avaliação",
                tutorial = "Esses itens podem ser observados ao longo da avaliação, mas é necessário observar a criança quanto a quantidade e qualidade dos movimentos. Algumas crianças terão movimentos ligeiramente espasmódicos (espasmos), ou seja, a coluna 3, mas raramente eles caem na coluna 4. Se você julgar que os movimentos não são ideais, mas não se encaixam na coluna 3 então coloque-os na coluna 2. Observe que os itens neste seção não são o mesmo que uma Avaliação dos Movimentos Gerais. É mais uma impressão geral do período em que você está observando a criança – também a maioria das crianças que você está avaliando não está dentro da faixa etária da avaliação do GM.",
                textScore3 = "Livre, alternado e suave",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Brusco; Leve tremor",
                textScore0 = "Rígido e sincrônico; Espasmos extensores; Atetóide; Atáxico; Muito trêmulo; Espasmo mioclônico; Movimento distônico",
            ),
        )
    ),

    Evaluation(
        title = "TÔNUS",
        section = "SEÇÃO 1: EXAME NEUROLÓGICO",
        exams = listOf(
            Exam(
                title = "Sinal do cachecol",
                tutorial = "Esta seção deve ser feita com a criança deitada em uma cama, um colchonete ou no chão. No entanto, se a criança estiver muito relutante em se deitar na cama/ chão, você pode fazer isso colocando a criança no colo de sua mãe e do pai / responsável (como mostrado no vídeo). É melhor fazer isso sentando-se em uma cadeira em frente ao cuidador para que seus joelhos estejam quase se tocando e, em seguida, sente a criança no colo do cuidador e, puxe as pernas lentamente em sua direção para que a criança esteja deitada sobre as suas duas pernas. Você pode ser capaz de avaliar alguns itens desta maneira. Sempre registre as assimetrias. Puxe o braço pela linha média em frente ao peito suavemente, mas com firmeza. Mantenha a cabeça da criança na linha média e veja se o cotovelo chega até a borda externa da bochecha (coluna 3), até o meio da bochecha ipsilateral, até o queixo ou cruza a linha média até o meio da bochecha contralateral. (marque tudo na coluna 1, o desenho à esquerda, entre os dois ou o desenho à direita, conforme observado). A maioria das crianças estará à direita da coluna 1, mas muitas estão na coluna 3 porque o tono baixo ao redor dos ombros permite que o cotovelo se estenda até a borda externa ou além da bochecha contralateral. De um modo geral, em bebês  mais novos, o cotovelo se moverá em direção à linha média, mas em bebês mais velhos pode ir além.",
                subtitle = "Pegue a mão da criança e puxe o braço sobre o peito até encontrar resistência. Observe a posição do cotovelo em relação à linha média.",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                imageId3 = Triple(Pair(R.drawable.bg_img_303_f, R.drawable.bg_img_303_m), null, R.drawable.bg_img_alt_303),
                imageId2 = Triple(Pair(R.drawable.bg_img_303_f, R.drawable.bg_img_303_m), Pair(R.drawable.bg_img_301_f, R.drawable.bg_img_301_m), null),
                imageId1 = Triple(Pair(R.drawable.bg_img_301_f, R.drawable.bg_img_301_m), null, R.drawable.bg_img_alt_301),
                imageId0 = Triple(Pair(R.drawable.bg_img_300_f, R.drawable.bg_img_300_m), null, R.drawable.bg_img_alt_300),
            ),
            Exam(
                title = "Elevação passiva do ombro",
                subtitle = "Levante o braço ao lado da cabeça da criança. Observe a resistência no ombro e cotovelo.",
                tutorial = "Segure o braço pelo punho, levante-o verticalmente até ficar ao lado da cabeça na cama. Às vezes você encontra alguma resistência, que pode ser facilmente superada (coluna 1), mas muitas vezes, em crianças pré-termo, pouca resistência é atingida nessa manobra (coluna 3). Repita a manobra de elevação passiva do ombro de cada lado para sentir assimetrias leves. Evite fazer um movimento circular como se estivesse avaliando os movimentos de extensão do ombro, apenas levante o braço ao longo do lado da cabeça.",
                textScore3 = "Resistência superável",
                textScore2 = "Resistência difícil de superar",
                textScore1 = "Sem resistência",
                textScore0 = "Resistência, não superável",
                imageId3 = Triple(Pair(R.drawable.bg_img_313_f, R.drawable.bg_img_313_m), null, R.drawable.bg_img_alt_313),
                imageId2 = Triple(Pair(R.drawable.bg_img_313_f, R.drawable.bg_img_313_m), Pair(R.drawable.bg_img_311_f, R.drawable.bg_img_311_m), null),
                imageId1 = Triple(Pair(R.drawable.bg_img_311_f, R.drawable.bg_img_311_m), null, R.drawable.bg_img_alt_311),
                imageId0 = Triple(Pair(R.drawable.bg_img_310_f, R.drawable.bg_img_310_m), null, R.drawable.bg_img_alt_310),
            ),
            Exam(
                title = "Pronação/supinação",
                subtitle = "Estabilize o braço enquanto é feito a pronação e supinação no antebraço, observe a resistência.",
                tutorial = "Estenda o cotovelo o máximo possível e em seguida, segure o braço logo abaixo do cotovelo com uma das mãos, com a outra mão segure o punho e gire o antebraço da criança no punho supinando-o e pronando-o em 180 °",
                textScore3 = "Pronação completa e supinação, sem resistência",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Resistência total à pronação completa/supinação superável",
                textScore0 = "Não é possível pronação completa e supinação, resistência acentuada",
            ),
            Exam(
                title = "Adutores de quadril",
                subtitle = "Com as duas pernas da criança estendidas, faça abdução de ambos os membros, o mais distante possível. Observe o ângulo formado pelas pernas.",
                tutorial = "Deite a criança na horizontal preferencialmente de fralda solta. Mantenha as pernas retas no quadril e joelho e juntas na linha média e em seguida, suavemente abduza-os o máximo que puder, mantendo as pernas alinhadas com a cama, ou seja, não flexione os quadris e lembre-se de manter os joelhos estendidos.",
                textScore3 = "Amplitude: 150º-80º",
                textScore2 = "Amplitude: 150º-160º",
                textScore1 = "Amplitude: >170º",
                textScore0 = "Ampiltude: <80º",
                imageId3 = Triple(Pair(R.drawable.bg_img_333_f, R.drawable.bg_img_333_m), null, R.drawable.bg_img_alt_333),
                imageId2 = Triple(Pair(R.drawable.bg_img_332_f, R.drawable.bg_img_332_m), null, R.drawable.bg_img_alt_332),
                imageId1 = Triple(Pair(R.drawable.bg_img_331_f, R.drawable.bg_img_331_m), null, R.drawable.bg_img_alt_331),
                imageId0 = Triple(Pair(R.drawable.bg_img_330_f, R.drawable.bg_img_330_m), null, R.drawable.bg_img_alt_330),
            ),
            Exam(
                title = "Ângulo poplíteo",
                subtitle = "Mantendo as nádegas da criança na cama, flexione os quadris sobre o abdômen, depois estenda os joelhos até encontrar resistência. Observe o ângulo entre a parte superior e inferior da perna.",
                tutorial = "Deite a criança de costas. Flexione os quadris de modo que a parte anterior das coxas toque o abdômen, mantendo a parte inferior da criança em contato com a cama o máximo possível - se você deixar a parte inferior se levantar, o ângulo poplíteo medido será maior.Então, mantendo as coxas no abdômen, estenda a parte inferior das pernas até onde os joelhos vão facilmente e estime o ângulo atrás do joelho. O teste foi padronizado testando-se as 2 pernas juntas. Se não for possível (ex.se a criança está se contorcendo muito ou insiste em estender as pernas), então você pode testar uma perna de cada vez, o que torna mais fácil manter a criança na cama, mas anote que você fez desta maneira e tenha cuidado para procurar assimetrias.",
                textScore3 = "Amplitude: 150º-100º",
                textScore2 = "Amplitude: 150º-160º",
                textScore1 = "Amplitude: ~90º ou >170º",
                textScore0 = "Amplitude: <80º",
                imageId3 = Triple(Pair(R.drawable.bg_img_343_f, R.drawable.bg_img_343_m), null, R.drawable.bg_img_alt_343),
                imageId2 = Triple(Pair(R.drawable.bg_img_342_f, R.drawable.bg_img_342_m), null, R.drawable.bg_img_alt_342),
                imageId1 = Triple(Pair(R.drawable.bg_img_341_f, R.drawable.bg_img_341_m), null, R.drawable.bg_img_alt_341),
                imageId0 = Triple(Pair(R.drawable.bg_img_340_f, R.drawable.bg_img_340_m), null, R.drawable.bg_img_alt_340),
            ),
            Exam(
                title = "Dorsiflexão de tornozelo",
                subtitle = "Com o joelho estendido, faça dorsiflexão do tornozelo. Observe o ângulo entre o pé e a perna.",
                tutorial = "É importante fazer o teste com a perna esticada na altura do joelho e do quadril. Segure o joelho na cama, colocando a palma de uma mão na patela e ao mesmo tempo, coloque a outra mão aberta contra a sola do pé, faça a dorsiflexão o tornozelo até onde for naturalmente. Tenha cuidado para não provocar o reflexo de preensão plantar. Estime o ângulo entre o dorso do pé e a canela (parte inferior da perna). Algumas crianças resistirão voluntariamente a essa manobra, mas na verdade serão bastante flexíveis, então faça isso devagar, mas com firmeza. Algumas crianças terão uma resistência involuntária e, em seguida, repentinamente cederão - se esse for o caso, anote na coluna de comentários. Você também pode testar o clônus, mas isso não faz parte deste ítem.",
                textScore3 = "Amplitude: 30º-85º",
                textScore2 = "Amplitude: 20º-160º",
                textScore1 = "Amplitude: <20º ou 90º",
                textScore0 = "Amplitude: >90º",
                imageId3 = Triple(Pair(R.drawable.bg_img_353_f, R.drawable.bg_img_353_m), null, R.drawable.bg_img_alt_353),
                imageId2 = Triple(Pair(R.drawable.bg_img_352_f, R.drawable.bg_img_352_m), null, R.drawable.bg_img_alt_352),
                imageId1 = Triple(Pair(R.drawable.bg_img_351_f, R.drawable.bg_img_351_m), null, R.drawable.bg_img_alt_351),
                imageId0 = Triple(Pair(R.drawable.bg_img_350_f, R.drawable.bg_img_350_m), null, R.drawable.bg_img_alt_350),
            ),
            Exam(
                title = "Puxado para sentar",
                subtitle = "Puxe a criança para sentar pelos punhos (se necessário, apoie a cabeça)Puxe a criança para sentar pelos punhos (se necessário, apoie a cabeça)",
                tutorial = "Segure a criança pelos punhos e levante-a observando a posição da cabeça a medida que sobe, se você sentir que ele teve uma resposta inferior repita a manobra. Este item pode ser difícil de pontuar se o bebê estiver chorando e deliberadamente jogando a cabeça para trás, repita quando o bebê estiver mais calmo. Se eles são muito flexíveis (hipotônicos) certifique-se de manter a mão sob a cabeça para dar o apoio necessário.",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                imageId3 = Triple(Pair(R.drawable.bg_img_363_f, R.drawable.bg_img_363_m), null, R.drawable.bg_img_alt_363),
                imageId2 = Triple(Pair(R.drawable.bg_img_363_f, R.drawable.bg_img_363_m), Pair(R.drawable.bg_img_361_f, R.drawable.bg_img_361_m), null),
                imageId1 = Triple(Pair(R.drawable.bg_img_361_f, R.drawable.bg_img_361_m), null, R.drawable.bg_img_alt_361),
                imageId0 = Triple(Pair(R.drawable.bg_img_360_f, R.drawable.bg_img_360_m), null, R.drawable.bg_img_alt_360),
            ),
            Exam(
                title = "Suspensão ventral",
                subtitle = "Segure a criança horizontalmente, em suspensão ventral, com as mãos ao redor do tronco; observe a posição da coluna, membros e cabeça.",
                tutorial = "Segure a criança ao redor do abdômen em uma posição horizontal. Algumas das crianças podem ser muito pesadas para serem seguradas confortavelmente ao redor do abdômen nessa posição. Elas também podem mexer ou não gostar de ser levantadas no ar e ter a impressão de cair, se isso acontecer, anote isso em vez de pontuar o item e repita o teste quando a criança estiver mais receptiva.",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                imageId3 = Triple(Pair(R.drawable.bg_img_373_f, R.drawable.bg_img_373_m), null, R.drawable.bg_img_alt_373),
                imageId2 = Triple(Pair(R.drawable.bg_img_373_f, R.drawable.bg_img_373_m), Pair(R.drawable.bg_img_371_f, R.drawable.bg_img_371_m), null),
                imageId1 = Triple(Pair(R.drawable.bg_img_371_f, R.drawable.bg_img_371_m), null, R.drawable.bg_img_alt_371),
                imageId0 = Triple(Pair(R.drawable.bg_img_370_f, R.drawable.bg_img_370_m), null, R.drawable.bg_img_alt_370),
            ),
        )
    ),

    Evaluation(
        title = "REFLEXOS E REAÇÕES",
        section = "SEÇÃO 1: EXAME NEUROLÓGICO",
        exams = listOf(
            Exam(
                title = "Proteção do braço",
                subtitle = "Puxe a criança por um braço na posição supina (estabilize o quadril contralateral) e observe a reação do braço no lado oposto.",
                tutorial = "Para fazer o teste deite o bebê, coloque a mão no quadril contralateral ao braço pelo qual você o puxará. Em seguida, puxe-o lentamente para cima pelo punho e veja se ele coloca o braço livre na cama para se apoiar. Para marcar 3 eles precisam abrir a mão e espalhar os dedos e suporte de peso na superfície. Repita o contrário para testar o outro lado. Observe que a resposta da proteção do braço não é a mesma que a proteção lateral, resposta que é provocada quando a criança está sentada e estende o braço para se proteger quando inclinado para o lado. Se uma criança estiver muito hipotônica, faça isso com cuidado extra e não persista se não houver resposta precoce ou parece doer, por exemplo o ombro que você está puxando para cima. Esteja também ciente de que o braço pode simplesmente cair na cama. É preciso haver um componente ativo na resposta para pontuar. Qualquer criança que consiga sentar-se de forma independente e estável deve ter uma resposta de proteção do braço, embora possa ser melhor de um lado do que do outro. Algumas crianças mais velhas não respondem “salvando-se” porque gostam de brincar e cair. Descreva na folha de registro, se você achar que é este o caso, em vez de avaliá-los incorretamente. Se eles obviamente fazem isso, marque a reação na coluna 1 (pontuação 3).",
                textScore3 = "Braço e mão estendidos",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Braço semiflexionado",
                textScore0 = "Braço completamente flexionado",
                imageId3 = Triple(Pair(R.drawable.bg_img_403_f, R.drawable.bg_img_403_m), null, R.drawable.bg_img_alt_403),
                imageId2 = Triple(Pair(R.drawable.bg_img_403_f, R.drawable.bg_img_403_m), Pair(R.drawable.bg_img_401_f, R.drawable.bg_img_401_m), null),
                imageId1 = Triple(Pair(R.drawable.bg_img_401_f, R.drawable.bg_img_401_m), null, R.drawable.bg_img_alt_401),
                imageId0 = Triple(Pair(R.drawable.bg_img_400_f, R.drawable.bg_img_400_m), null, R.drawable.bg_img_alt_400),
            ),
            Exam(
                title = "Suspensão vertical",
                subtitle = "Segure a criança embaixo das axilas, não deixando que as pernas toquem na superfície – você pode fazer “cócegas” nos pés para estimular os chutes.",
                tutorial = "Segure a criança verticalmente logo abaixo das axilas, de costas para você, para que eles possam ver seus pais ou cuidadores, e observe se eles chutam as pernas igualmente e bem. Às vezes é necessário fazer com que alguém estimule (faça cócegas) os pés para encorajar uma resposta. Uma delas é principalmente procurar diferenças sutis se elas chutam uma perna mais do que a outra. Se eles são muito pesados para levantar ou deliberadamente se soltam ou endurecem, descreva isso e não marque pontos. Chutar nesta posição não é o mesmo que chutar na horizontal ou quando estão sentados – é uma tarefa mais difícil. Você pode pedir ao pai/responsável para segurar o bebê desta maneira se preferir.",
                textScore3 = "Chuta simetricamente",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                textScore1 = "Chuta mais uma perna ou chutes fracos",
                textScore0 = "Não chuta mesmo que estimulado ou em posição de tesoura",
                imageId3 = Triple(Pair(R.drawable.bg_img_413_f, R.drawable.bg_img_413_m), null, R.drawable.bg_img_alt_413),
                imageId2 = Triple(Pair(R.drawable.bg_img_413_f, R.drawable.bg_img_413_m), Pair(R.drawable.bg_img_411_f, R.drawable.bg_img_411_m), null),
                imageId1 = Triple(Pair(R.drawable.bg_img_411_f, R.drawable.bg_img_411_m), null, R.drawable.bg_img_alt_411),
                imageId0 = Triple(Pair(R.drawable.bg_img_410_f, R.drawable.bg_img_410_m), null, R.drawable.bg_img_alt_410),
            ),
            Exam(
                title = "Inclinação lateral",
                subtitle = "(descreva o lado que está para cima). Segure a criança verticalmente próximo dos quadris e incline lateralmente em direção horizontal. Observe a resposta do tronco, coluna, membros e cabeça.",
                tutorial = "Segure a criança logo acima dos quadris, (não abaixo das axilas) com as costas voltadas para você, de modo que esteja de frente para o pai / responsável. Em seguida o incline para o lado (não rápido) cerca de 45°, e veja/ sinta a resposta do músculo do tronco sob sua mão superior. Algumas crianças mais velhas podem ser muito  pesadas para levantar e algumas podem se soltar deliberadamente. Para pontuar na coluna 1 – Pontuação 3 (veja o desenho), eles devem ter uma resposta rápida não apenas com o tronco, mas também com a elevação das pernas e dos ombros. Lembrese, você não deve incliná-lo muito rápido ou deixá-lo completamente na horizontal.",
                imageId3 = Triple(Pair(R.drawable.bg_img_423_f, R.drawable.bg_img_423_m), null, R.drawable.bg_img_alt_423),
                imageId2 = Triple(Pair(R.drawable.bg_img_422_f, R.drawable.bg_img_422_m), null, R.drawable.bg_img_alt_422),
                imageId1 = Triple(Pair(R.drawable.bg_img_421_f, R.drawable.bg_img_421_m), null, R.drawable.bg_img_alt_421),
                imageId0 = Triple(Pair(R.drawable.bg_img_420_f, R.drawable.bg_img_420_m), null, R.drawable.bg_img_alt_420),
            ),
            Exam(
                title = "Paraquedas anterior (após 6 meses)",
                subtitle = "Segure a criança verticalmente e rapidamente incline-a para frente. Observe a reação/simetria da resposta dos braços.",
                tutorial = "Segure a criança logo acima da cintura e incline-a rapidamente para a frente em direção a uma cama ou mesa. Procure uma resposta simétrica do braço para frente e as mãos abertas na superfície. A resposta raramente está presente antes dos 6 meses de idade pós termo e até então o ítem não precisa ser testado e a pontuação será 0. Depois desta idade ou pontue 3 se a reação estiver presente e simétrica ou pontue 1 se ausente. Se parcial (por exemplo, mãos ainda em garra) pontue 2, bem como se apresentar assimetrias (observe em qual lado é presente/ausente e marque a A na coluna da direita).",
                textScore2 = "As características observadas, embora melhores que as do Score 01, são inferiores às do Score 03.",
                imageId3 = Triple(Pair(R.drawable.bg_img_433_f, R.drawable.bg_img_433_m), null, R.drawable.bg_img_alt_433),
                imageId2 = Triple(Pair(R.drawable.bg_img_433_f, R.drawable.bg_img_433_m), Pair(R.drawable.bg_img_431_f, R.drawable.bg_img_431_m), null),
                imageId1 = Triple(Pair(R.drawable.bg_img_431_f, R.drawable.bg_img_431_m), null, R.drawable.bg_img_alt_431),
            ),
            Exam(
                title = "Reflexos tendinosos",
                subtitle = "Com a criança relaxada, sentada ou deitada – use um martelo pequeno",
                tutorial = "A melhor maneira de testar é com a criança deitada, mas os testes podem ser feitos em outras posições. O mais importante é que os músculos ao redor do tendão a ser testado estejam relaxados. Pode ser difícil usar o martelo com algumas crianças e, nestes casos, é melhor bater com os dedos no tendão quando a criança relaxa (você precisa de prática para realizar assim).Tenha sempre o cuidado de bater no tendão e não na patela ou no calcanhar que é doloroso. Para o bíceps segure o cotovelo e coloque o polegar sobre o tendão e percuta sobre o dedo. Ocasionalmente você pode sentir o reflexo mas não observá-lo (movimento), isto pode ser considerado como normal.",
                textScore3 = "Facilmente excitável: bíceps; joelho; tornozelo; (reflexos normais)",
                textScore2 = "Levemente ativo: bíceps; joelho; tornozelo; (reflexos hipoativos)",
                textScore1 = "Ativo: bíceps; joelho; tornozelo; (reflexos hiperativos)",
                textScore0 = "Clônus ou ausente: bíceps; joelho; tornozelo",
            ),
        )
    ),
    Evaluation(
        title = "MARCOS MOTORES",
        section = "SEÇÃO 2: MARCOS MOTORES",
        scored = false,
        exams = listOf(
            Exam(
                title = "Controle da cabeça",
                tutorial = "Nós não pontuamos esses itens, mas eles agem como um registro do desenvolvimento motor e do estado durante o exame. As imagens e descrições dos marcos motores são óbvias. ▪ Pergunte se a criança brincou com os dedos dos pés quando era mais jovem - observe alguma assimetria. ▪ Pergunte se a criança rola para os dois sentidos e lados – novamente observe assimetrias. ▪ Faça um comentário se eles apenas engatinham e se eles rastejam aleatoriamente. ▪ Observe a idade da caminhada independente (5 passos).",
                textScore0 = "Incapaz de manter a cabeça levantada; Normal aos 3 meses",
                textScore1 = "Oscilações; Normal até 4 meses",
                textScore2 = "Mantém a cabeça ereta todo o tempo; Normal a partir de 5 meses",
                maxScore = 2
            ),
            Exam(
                title = "Sentar",
                tutorial = "Nós não pontuamos esses itens, mas eles agem como um registro do desenvolvimento motor e do estado durante o exame. As imagens e descrições dos marcos motores são óbvias. ▪ Pergunte se a criança brincou com os dedos dos pés quando era mais jovem - observe alguma assimetria. ▪ Pergunte se a criança rola para os dois sentidos e lados – novamente observe assimetrias. ▪ Faça um comentário se eles apenas engatinham e se eles rastejam aleatoriamente. ▪ Observe a idade da caminhada independente (5 passos).",
                textScore0 = "Não pode sentar",
                textScore1 = "Com suporte nos quadris; Normal aos 4 meses",
                textScore2 = "Escorado; Normal aos 6 meses",
                textScore3 = "Senta-se estável; Normal aos 7-8 meses",
                textScore4 = "Pivoteia (gira); Normal aos 9 meses",
                imageId4 = Triple(Pair(R.drawable.bg_img_514_f, R.drawable.bg_img_514_m), null, R.drawable.bg_img_alt_514),
                imageId3 = Triple(Pair(R.drawable.bg_img_513_f, R.drawable.bg_img_513_m), null, R.drawable.bg_img_alt_513),
                imageId2 = Triple(Pair(R.drawable.bg_img_512_f, R.drawable.bg_img_512_m), null, R.drawable.bg_img_alt_512),
                imageId1 = Triple(Pair(R.drawable.bg_img_511_f, R.drawable.bg_img_511_m), null, R.drawable.bg_img_alt_511),
                maxScore = 4
            ),
            Exam(
                title = "Preensão voluntária",
                subtitle = "observe o lado",
                tutorial = "Nós não pontuamos esses itens, mas eles agem como um registro do desenvolvimento motor e do estado durante o exame. As imagens e descrições dos marcos motores são óbvias. ▪ Pergunte se a criança brincou com os dedos dos pés quando era mais jovem - observe alguma assimetria. ▪ Pergunte se a criança rola para os dois sentidos e lados – novamente observe assimetrias. ▪ Faça um comentário se eles apenas engatinham e se eles rastejam aleatoriamente. ▪ Observe a idade da caminhada independente (5 passos).",
                textScore0 = "Sem preensão",
                textScore1 = "Usa toda mão",
                textScore2 = "Dedo indicador e polegar, mas preensão imatura",
                textScore3 = "Preensão em pinça",
            ),
            Exam(
                title = "Habilidade de chutar em supino",
                tutorial = "Nós não pontuamos esses itens, mas eles agem como um registro do desenvolvimento motor e do estado durante o exame. As imagens e descrições dos marcos motores são óbvias. ▪ Pergunte se a criança brincou com os dedos dos pés quando era mais jovem - observe alguma assimetria. ▪ Pergunte se a criança rola para os dois sentidos e lados – novamente observe assimetrias. ▪ Faça um comentário se eles apenas engatinham e se eles rastejam aleatoriamente. ▪ Observe a idade da caminhada independente (5 passos).",
                textScore0 = "Não chuta",
                textScore1 = "Chuta horizontalmente, mas não eleva as pernas",
                textScore2 = "Para cima (verticalmente); Normal aos 3 meses",
                textScore3 = "Toca a perna; Normal aos 4-5 meses",
                textScore4 = "Toca nos dedos dos pés; Normal aos 5-6 meses",
                imageId4 = Triple(Pair(R.drawable.bg_img_534_f, R.drawable.bg_img_534_m), null, R.drawable.bg_img_alt_534),
                imageId3 = Triple(Pair(R.drawable.bg_img_533_f, R.drawable.bg_img_533_m), null, R.drawable.bg_img_alt_533),
                imageId2 = Triple(Pair(R.drawable.bg_img_532_f, R.drawable.bg_img_532_m), null, R.drawable.bg_img_alt_532),
                maxScore = 4
            ),
            Exam(
                title = "Rolar",
                subtitle = "observe para qual lado",
                tutorial = "Nós não pontuamos esses itens, mas eles agem como um registro do desenvolvimento motor e do estado durante o exame. As imagens e descrições dos marcos motores são óbvias. ▪ Pergunte se a criança brincou com os dedos dos pés quando era mais jovem - observe alguma assimetria. ▪ Pergunte se a criança rola para os dois sentidos e lados – novamente observe assimetrias. ▪ Faça um comentário se eles apenas engatinham e se eles rastejam aleatoriamente. ▪ Observe a idade da caminhada independente (5 passos).",
                textScore0 = "Não rola",
                textScore1 = "Rola para o lado; Normal aos 4 meses",
                textScore2 = "Rola de prono para supino; Normal aos 6 meses",
                textScore3 = "Rola de supino para prono; Normal aos 6 meses",
            ),
            Exam(
                title = "Engatinhar",
                subtitle = "observe se arrasta sentado",
                tutorial = "Nós não pontuamos esses itens, mas eles agem como um registro do desenvolvimento motor e do estado durante o exame. As imagens e descrições dos marcos motores são óbvias. ▪ Pergunte se a criança brincou com os dedos dos pés quando era mais jovem - observe alguma assimetria. ▪ Pergunte se a criança rola para os dois sentidos e lados – novamente observe assimetrias. ▪ Faça um comentário se eles apenas engatinham e se eles rastejam aleatoriamente. ▪ Observe a idade da caminhada independente (5 passos).",
                textScore0 = "Não levanta a cabeça",
                textScore1 = "Com cotovelo; Normal aos 3 meses",
                textScore2 = "Com os braços e mãos super estendidos; Normal aos 4 meses",
                textScore3 = "Engatinha com abdômen; Normal aos 8 meses",
                textScore4 = "Engatinha sobre mãos e joelhos; Normal aos 10 meses",
                imageId4 = Triple(Pair(R.drawable.bg_img_554_f, R.drawable.bg_img_554_m), null, R.drawable.bg_img_alt_554),
                imageId3 = Triple(Pair(R.drawable.bg_img_553_f, R.drawable.bg_img_553_m), null, R.drawable.bg_img_alt_553),
                imageId2 = Triple(Pair(R.drawable.bg_img_552_f, R.drawable.bg_img_552_m), null, R.drawable.bg_img_alt_552),
                imageId1 = Triple(Pair(R.drawable.bg_img_551_f, R.drawable.bg_img_551_m), null, R.drawable.bg_img_alt_551),
                maxScore = 4
            ),
            Exam(
                title = "Em pé",
                tutorial = "Nós não pontuamos esses itens, mas eles agem como um registro do desenvolvimento motor e do estado durante o exame. As imagens e descrições dos marcos motores são óbvias. ▪ Pergunte se a criança brincou com os dedos dos pés quando era mais jovem - observe alguma assimetria. ▪ Pergunte se a criança rola para os dois sentidos e lados – novamente observe assimetrias. ▪ Faça um comentário se eles apenas engatinham e se eles rastejam aleatoriamente. ▪ Observe a idade da caminhada independente (5 passos).",
                textScore0 = "Não sustenta o peso",
                textScore1 = "Sustenta o peso; Normal aos 4 meses",
                textScore2 = "Em pé com apoio; Normal aos 7 meses",
                textScore3 = "Em pé sem ajuda; Normal aos 12 meses",
            ),
            Exam(
                title = "Marcha",
                tutorial = "Nós não pontuamos esses itens, mas eles agem como um registro do desenvolvimento motor e do estado durante o exame. As imagens e descrições dos marcos motores são óbvias. ▪ Pergunte se a criança brincou com os dedos dos pés quando era mais jovem - observe alguma assimetria. ▪ Pergunte se a criança rola para os dois sentidos e lados – novamente observe assimetrias. ▪ Faça um comentário se eles apenas engatinham e se eles rastejam aleatoriamente. ▪ Observe a idade da caminhada independente (5 passos).",
                textScore1 = "Saltando; Normal aos 6 meses",
                textScore2 = "Marcha lateral (se segurando); Normal aos 12 meses",
                textScore3 = "Marcha independente: Normal aos 15 meses",
            ),
        )
    ),
    Evaluation(
        title = "COMPORTAMENTO",
        section = "SEÇÃO 3: COMPORTAMENTO",
        scored = false,
        exams = listOf(
            Exam(
                title = "Estado consciente",
                tutorial = "As observações na seção de comportamento são numeradas de 1 a 6 para estado de consciência, de 1 a 5 para estado emocional e 1 a 4 para orientação social. Isso totaliza no máximo 15 pontos e pode ser anotado na folha de rosto. Embora as informações nesta seção sejam importantes e úteis não fazem parte da pontuação HINE.",
                textScore0 = "Irritado",
                textScore1 = "Sonolento",
                textScore2 = "Dormindo, mas acorda facilmente",
                textScore3 = "Acordado, mas sem interesse",
                textScore4 = "Perde interesse",
                textScore5 = "Mantém interesse",
                maxScore = 5
            ),
            Exam(
                title = "Estado emocional",
                tutorial = "As observações na seção de comportamento são numeradas de 1 a 6 para estado de consciência, de 1 a 5 para estado emocional e 1 a 4 para orientação social. Isso totaliza no máximo 15 pontos e pode ser anotado na folha de rosto. Embora as informações nesta seção sejam importantes e úteis não fazem parte da pontuação HINE.",
                textScore0 = "Irritável, não consolável",
                textScore1 = "Irritável, cuidador pode consolar",
                textScore2 = "Irritável quando se aproxima",
                textScore3 = "Nem feliz ou infeliz",
                textScore4 = "Feliz e sorridente",
                maxScore = 4
            ),
            Exam(
                title = "Orientação social",
                tutorial = "As observações na seção de comportamento são numeradas de 1 a 6 para estado de consciência, de 1 a 5 para estado emocional e 1 a 4 para orientação social. Isso totaliza no máximo 15 pontos e pode ser anotado na folha de rosto. Embora as informações nesta seção sejam importantes e úteis não fazem parte da pontuação HINE.",
                textScore0 = "Evitando, retirando",
                textScore1 = "Hesitante",
                textScore2 = "Aceita aproximação",
                textScore3 = "Amigável",
            ),
        )
    )
)
